package br.com.nazareth.Catalogo.model.product;

public enum TipoAlimento {
    FRUTAS_E_VEGETAIS,
    CARNES_E_PESCADOS,
    LATICINIOS,
    OVOS,
    PAES_FRESCOS_E_PADARIA,

    GRAOS,
    ENLATADOS,
    PRODUTOS_SECOS,
    TEMPEROS_E_CONDIMENTOS,
    PRODUTOS_DE_CONFEITARIA,

    LEGUMES_E_VEGETAIS_CONGELADOS,
    CARNES_E_AVES_CONGELADAS,
    PRATOS_PRONTOS_CONGELADOS,
    SORVETES_E_DESERTES_CONGELADOS,

    SUCOS_E_REFRIGERANTES,
    BEBIDAS_ALCOOLICAS,
    CAFÉ_E_CHÁS,

    ALIMENTOS_SEM_GLUTEN,
    ALIMENTOS_SEM_LACTOSE,
    PRODUTOS_ORGANICOS,
    ALIMENTOS_VEGANOS_OU_VEGETARIANOS;
}

